### ISSUE TITLE
Crashes during launch on iOS 17

### ISSUE THREAD

**Issue by iBringit** [Lessica/TrollSpeed#7] opened 2023-12-12 02:07 UTC
So I upgraded to iOS 17 with TrollStore.
After update, I tried installing Trollspeed with TrollStore, but right after I decided to open the app, it just closes without launching.

Does it support iOS 17 with TrollStore?

**Comment by Lessica** [comment] 2023-12-12 06:03
Duplicate of https://github.com/Lessica/TrollSpeed/issues/3

**Closed** 2023-12-12 06:04 UTC
