### ISSUE TITLE
don't work on ios17.0

### ISSUE THREAD

**Issue by jeje9527** [Lessica/TrollSpeed#5] opened 2023-12-07 19:19 UTC
![IMG_1478](https://github.com/Lessica/TrollSpeed/assets/48116066/7bc884ad-32f6-40f0-bbd0-d7c7490aaa9c)

**Comment by Lessica** [comment] 2023-12-08 00:51
Tested on iOS 17.0, works perfectly. Possibly a duplicate of https://github.com/Lessica/TrollSpeed/issues/3

**Closed** 2023-12-08 00:51 UTC
